motto: "What is dead may never die."

server:
  applicationConnectors:
    - type: http
      port: 8080

logging:
  level: INFO
  appenders:
    - type: console
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      timeZone: UTC
